name: rakshak_sense
description: "RakshakSense - AI-Based Predictive Personnel Stress and Welfare Monitoring System for Uniformed Forces (SIH26186 - MHA / CRPF)."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
